const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const environmentsDir = path.join(__dirname, 'src', 'environments');
const envFilePath = path.join(environmentsDir, 'environment.ts');

console.log('Running set-env.js to generate Angular environment file...');

// Create environments directory if it doesn't exist
if (!fs.existsSync(environmentsDir)) {
  fs.mkdirSync(environmentsDir, { recursive: true });
}

let supabaseUrl = '';
let supabaseAnonKey = '';

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  envContent.split('\n').forEach(line => {
    const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
    if (match) {
      const key = match[1];
      let value = match[2] || '';
      if (value.startsWith('"') && value.endsWith('"')) {
        value = value.slice(1, -1);
      } else if (value.startsWith("'") && value.endsWith("'")) {
        value = value.slice(1, -1);
      }
      
      if (key === 'Vaarunya_angular_imgs_storage_SUPABASE_URL') {
        supabaseUrl = value;
      } else if (key === 'NEXT_PUBLIC_Vaarunya_angular_imgs_storage_SUPABASE_ANON_KEY') {
        supabaseAnonKey = value;
      }
    }
  });
} else {
  console.warn('⚠️ No .env file found at:', envPath);
}

// Fallback to process.env if .env doesn't define them
supabaseUrl = supabaseUrl || process.env.Vaarunya_angular_imgs_storage_SUPABASE_URL || '';
supabaseAnonKey = supabaseAnonKey || process.env.NEXT_PUBLIC_Vaarunya_angular_imgs_storage_SUPABASE_ANON_KEY || '';

const envConfigFile = `// This file is auto-generated by set-env.js. Do not commit it.
export const environment = {
  production: false,
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}'
};
`;

try {
  fs.writeFileSync(envFilePath, envConfigFile, 'utf8');
  console.log(`✅ Generated environment.ts at ${envFilePath}`);
} catch (err) {
  console.error('❌ Failed to write environment.ts:', err);
  process.exit(1);
}
