const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const environmentsDir = path.join(__dirname, 'src', 'environments');
const envFilePath = path.join(environmentsDir, 'environment.ts');

console.log('Running set-env.js to generate Angular environment file...');

// Create environments directory if it doesn't exist
if (!fs.existsSync(environmentsDir)) {
  fs.mkdirSync(environmentsDir, { recursive: true });
}

function parseEnvFile(filePath) {
  let url = '';
  let keyVal = '';
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf8');
    content.split(/\r?\n/).forEach(line => {
      const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
      if (match) {
        const k = match[1];
        let val = match[2] || '';
        if (val.startsWith('"') && val.endsWith('"')) {
          val = val.slice(1, -1);
        } else if (val.startsWith("'") && val.endsWith("'")) {
          val = val.slice(1, -1);
        }
        
        if (k === 'NEXT_PUBLIC_SUPABASE_URL' || k === 'Vaarunya_angular_imgs_storage_SUPABASE_URL') {
          url = val;
        } else if (k === 'NEXT_PUBLIC_SUPABASE_ANON_KEY' || k === 'NEXT_PUBLIC_Vaarunya_angular_imgs_storage_SUPABASE_ANON_KEY') {
          keyVal = val;
        }
      }
    });
  }
  return { url, keyVal };
}

const stagingEnvPath = path.join(__dirname, '.env.staging');
const localEnvPath = path.join(__dirname, '.env');

let { url: supabaseUrl, keyVal: supabaseAnonKey } = parseEnvFile(stagingEnvPath);

if (!supabaseUrl || !supabaseAnonKey) {
  console.log('Checking fallback .env...');
  const localEnv = parseEnvFile(localEnvPath);
  if (!supabaseUrl) supabaseUrl = localEnv.url;
  if (!supabaseAnonKey) supabaseAnonKey = localEnv.keyVal;
}

// Fallback to process.env if files don't define them
supabaseUrl = supabaseUrl || process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.Vaarunya_angular_imgs_storage_SUPABASE_URL || '';
supabaseAnonKey = supabaseAnonKey || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_Vaarunya_angular_imgs_storage_SUPABASE_ANON_KEY || '';

const envConfigFile = `// This file is auto-generated by set-env.js. Do not commit it.
export const environment = {
  production: false,
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}'
};
`;

try {
  fs.writeFileSync(envFilePath, envConfigFile, 'utf8');
  console.log(`✅ Generated environment.ts at ${envFilePath}`);
} catch (err) {
  console.error('❌ Failed to write environment.ts:', err);
  process.exit(1);
}
